# Site settings
title: Long Do
description: Personal website powered by Jekyll
baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. https://example.com/
updated: 2020

# Landing Page
username: Long Do
typing_text: Front-End Developer
email: long.p.do@fau.de
github_username: longpdo
codepen_username: longpdo
dev_username:
linkedin_username: longpdo
twitter_username:

# About Me Section
show_aboutme_card: true
about_me_title: Who Am I
about_me_description:
  I'm a software developer primarly focusing on front-end development.
  I have experience working in agile environments and am a convinced advocate of clean code.
  My technical interests cover the integration of internet of things into everyday life,
  checking out open source projects and to automate repetitive processes via bash or python scripting.

# Skills Section
show_skills_card: true
skills_title: Skills

# Timeline Section
show_timeline_card: true
timeline_title: My Journey
cv_download_link: https://github.com/longpdo/Awesome-CV/blob/master/examples/cv.pdf

# Projects Section
show_projects_card: true
show_projects: false
projects_title: Things I Have Built
show_os_projects: true
os_projects_title: Things I Contributed To Open Source

# Github-Metadata
repository: longpdo/personal-website
projects:
  # pushed or stars
  sort_by: pushed
  exclude:
    archived: true
    forks: true
    projects:
    # - repo-name

# Google-analytics
google-analytics:
  id: "UA-158757509-1"

plugins:
  - "jekyll-github-metadata"

exclude:
  [
    "_assets",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "node_modules",
    "package.json",
  ]
